/* auto-generated stub for headless Qt testing */
#include <stddef.h>
long dbus_bus_add_match(void){return 0;}
long dbus_bus_get_private(void){return 0;}
long dbus_bus_get_unique_name(void){return 0;}
long dbus_bus_register(void){return 0;}
long dbus_bus_remove_match(void){return 0;}
long dbus_connection_add_filter(void){return 0;}
long dbus_connection_can_send_type(void){return 0;}
long dbus_connection_close(void){return 0;}
long dbus_connection_dispatch(void){return 0;}
long dbus_connection_get_is_authenticated(void){return 0;}
long dbus_connection_get_is_connected(void){return 0;}
long dbus_connection_open_private(void){return 0;}
long dbus_connection_ref(void){return 0;}
long dbus_connection_send(void){return 0;}
long dbus_connection_send_with_reply(void){return 0;}
long dbus_connection_set_allow_anonymous(void){return 0;}
long dbus_connection_set_dispatch_status_function(void){return 0;}
long dbus_connection_set_exit_on_disconnect(void){return 0;}
long dbus_connection_set_timeout_functions(void){return 0;}
long dbus_connection_set_watch_functions(void){return 0;}
long dbus_connection_unref(void){return 0;}
long dbus_error_free(void){return 0;}
long dbus_error_init(void){return 0;}
long dbus_error_is_set(void){return 0;}
long dbus_free(void){return 0;}
long dbus_get_local_machine_id(void){return 0;}
long dbus_message_copy(void){return 0;}
long dbus_message_get_allow_interactive_authorization(void){return 0;}
long dbus_message_get_error_name(void){return 0;}
long dbus_message_get_interface(void){return 0;}
long dbus_message_get_member(void){return 0;}
long dbus_message_get_no_reply(void){return 0;}
long dbus_message_get_path(void){return 0;}
long dbus_message_get_sender(void){return 0;}
long dbus_message_get_serial(void){return 0;}
long dbus_message_get_signature(void){return 0;}
long dbus_message_get_type(void){return 0;}
long dbus_message_iter_append_basic(void){return 0;}
long dbus_message_iter_append_fixed_array(void){return 0;}
long dbus_message_iter_close_container(void){return 0;}
long dbus_message_iter_get_arg_type(void){return 0;}
long dbus_message_iter_get_basic(void){return 0;}
long dbus_message_iter_get_element_type(void){return 0;}
long dbus_message_iter_get_fixed_array(void){return 0;}
long dbus_message_iter_get_signature(void){return 0;}
long dbus_message_iter_init(void){return 0;}
long dbus_message_iter_init_append(void){return 0;}
long dbus_message_iter_next(void){return 0;}
long dbus_message_iter_open_container(void){return 0;}
long dbus_message_iter_recurse(void){return 0;}
long dbus_message_new(void){return 0;}
long dbus_message_new_method_call(void){return 0;}
long dbus_message_new_signal(void){return 0;}
long dbus_message_ref(void){return 0;}
long dbus_message_set_allow_interactive_authorization(void){return 0;}
long dbus_message_set_auto_start(void){return 0;}
long dbus_message_set_destination(void){return 0;}
long dbus_message_set_error_name(void){return 0;}
long dbus_message_set_no_reply(void){return 0;}
long dbus_message_set_path(void){return 0;}
long dbus_message_set_reply_serial(void){return 0;}
long dbus_message_set_sender(void){return 0;}
long dbus_message_unref(void){return 0;}
long dbus_pending_call_block(void){return 0;}
long dbus_pending_call_cancel(void){return 0;}
long dbus_pending_call_get_completed(void){return 0;}
long dbus_pending_call_set_notify(void){return 0;}
long dbus_pending_call_steal_reply(void){return 0;}
long dbus_pending_call_unref(void){return 0;}
long dbus_server_allocate_data_slot(void){return 0;}
long dbus_server_disconnect(void){return 0;}
long dbus_server_free_data_slot(void){return 0;}
long dbus_server_get_address(void){return 0;}
long dbus_server_get_is_connected(void){return 0;}
long dbus_server_listen(void){return 0;}
long dbus_server_set_data(void){return 0;}
long dbus_server_set_new_connection_function(void){return 0;}
long dbus_server_set_timeout_functions(void){return 0;}
long dbus_server_set_watch_functions(void){return 0;}
long dbus_server_unref(void){return 0;}
long dbus_shutdown(void){return 0;}
long dbus_threads_init_default(void){return 0;}
long dbus_timeout_get_enabled(void){return 0;}
long dbus_timeout_get_interval(void){return 0;}
long dbus_timeout_handle(void){return 0;}
long dbus_watch_get_enabled(void){return 0;}
long dbus_watch_get_flags(void){return 0;}
long dbus_watch_get_unix_fd(void){return 0;}
long dbus_watch_handle(void){return 0;}
