/* auto-generated stub for headless Qt testing */
#include <stddef.h>
long glBindTexture(void){return 0;}
long glBlendFunc(void){return 0;}
long glClear(void){return 0;}
long glDeleteTextures(void){return 0;}
long glDisable(void){return 0;}
long glEnable(void){return 0;}
long glFlush(void){return 0;}
long glGenTextures(void){return 0;}
long glGetIntegerv(void){return 0;}
long glGetString(void){return 0;}
long glLoadIdentity(void){return 0;}
long glLoadMatrixf(void){return 0;}
long glMatrixMode(void){return 0;}
long glOrtho(void){return 0;}
long glPixelStorei(void){return 0;}
long glTexImage2D(void){return 0;}
long glTexParameterf(void){return 0;}
long glTexParameteri(void){return 0;}
long glTexSubImage2D(void){return 0;}
long glViewport(void){return 0;}
long glXChooseFBConfig(void){return 0;}
long glXChooseVisual(void){return 0;}
long glXCreateContext(void){return 0;}
long glXCreateNewContext(void){return 0;}
long glXCreatePbuffer(void){return 0;}
long glXDestroyContext(void){return 0;}
long glXDestroyPbuffer(void){return 0;}
long glXGetClientString(void){return 0;}
long glXGetConfig(void){return 0;}
long glXGetCurrentContext(void){return 0;}
long glXGetCurrentDisplay(void){return 0;}
long glXGetCurrentDrawable(void){return 0;}
long glXGetFBConfigAttrib(void){return 0;}
long glXGetProcAddress(void){return 0;}
long glXGetProcAddressARB(void){return 0;}
long glXGetVisualFromFBConfig(void){return 0;}
long glXMakeContextCurrent(void){return 0;}
long glXMakeCurrent(void){return 0;}
long glXQueryContext(void){return 0;}
long glXQueryExtensionsString(void){return 0;}
long glXSwapBuffers(void){return 0;}
