/* auto-generated stub for headless Qt testing */
#include <stddef.h>
long xkb_compose_state_feed(void){return 0;}
long xkb_compose_state_get_status(void){return 0;}
long xkb_compose_state_get_utf8(void){return 0;}
long xkb_compose_state_new(void){return 0;}
long xkb_compose_state_reset(void){return 0;}
long xkb_compose_state_unref(void){return 0;}
long xkb_compose_table_new_from_locale(void){return 0;}
long xkb_compose_table_unref(void){return 0;}
long xkb_context_new(void){return 0;}
long xkb_context_set_log_level(void){return 0;}
long xkb_context_unref(void){return 0;}
long xkb_keymap_get_as_string(void){return 0;}
long xkb_keymap_key_for_each(void){return 0;}
long xkb_keymap_key_get_syms_by_level(void){return 0;}
long xkb_keymap_key_repeats(void){return 0;}
long xkb_keymap_max_keycode(void){return 0;}
long xkb_keymap_min_keycode(void){return 0;}
long xkb_keymap_mod_get_index(void){return 0;}
long xkb_keymap_new_from_buffer(void){return 0;}
long xkb_keymap_new_from_names(void){return 0;}
long xkb_keymap_new_from_string(void){return 0;}
long xkb_keymap_num_layouts(void){return 0;}
long xkb_keymap_num_layouts_for_key(void){return 0;}
long xkb_keymap_unref(void){return 0;}
long xkb_keysym_get_name(void){return 0;}
long xkb_keysym_to_utf8(void){return 0;}
long xkb_state_get_keymap(void){return 0;}
long xkb_state_key_get_layout(void){return 0;}
long xkb_state_key_get_level(void){return 0;}
long xkb_state_key_get_one_sym(void){return 0;}
long xkb_state_key_get_utf8(void){return 0;}
long xkb_state_mod_index_is_active(void){return 0;}
long xkb_state_mod_name_is_active(void){return 0;}
long xkb_state_new(void){return 0;}
long xkb_state_serialize_layout(void){return 0;}
long xkb_state_serialize_mods(void){return 0;}
long xkb_state_unref(void){return 0;}
long xkb_state_update_key(void){return 0;}
long xkb_state_update_mask(void){return 0;}
long xkb_x11_get_core_keyboard_device_id(void){return 0;}
long xkb_x11_keymap_new_from_device(void){return 0;}
long xkb_x11_state_new_from_device(void){return 0;}
